[package]
name = "fathom-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
rusqlite.workspace = true
thiserror.workspace = true
uuid.workspace = true
time.workspace = true
dirs.workspace = true
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
