[package]
name = "pr-supervisor"
version.workspace = true
edition.workspace = true

[dependencies]
bollard.workspace = true
tokio.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
